### ISSUE TITLE
Testflight link?

### ISSUE THREAD

**Issue by SlinkousArt** [kukai-wallet/kukai-mobile-ios#13]
Is there a public testflight link, or will there be one?

**Comment by simonmcl** [comment]
@SlinkousArt apologies for the long delay, I didn't have notifications turned on for this repo. 

This project is in extremely early stages, and as of yet doesn't even have finalised designs. It mainly serves as a testbed for the library i'm writing and experimenting with ideas. Our public Beta plans haven't been set yet. If we do have hold a public beta, we would Tweet about it on twitter account ( https://twitter.com/kukaiwallet )
